# Generated by Django 6.0 on 2026-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0014_alter_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='resource',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='allowed_resources',
            field=models.TextField(blank=True, default='', help_text='Allowed resource server URIs list (RFC 8707), space separated'),
        ),
        migrations.AddField(
            model_name='grant',
            name='resource',
            field=models.TextField(blank=True, default=''),
        ),
    ]
