# Generated by Django 6.0 on 2026-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_sampledevicegrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="allowed_resources",
            field=models.TextField(
                blank=True, default="", help_text="Allowed resource server URIs list (RFC 8707), space separated"
            ),
        ),
        migrations.AddField(
            model_name="sampleaccesstoken",
            name="resource",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="allowed_resources",
            field=models.TextField(
                blank=True, default="", help_text="Allowed resource server URIs list (RFC 8707), space separated"
            ),
        ),
        migrations.AddField(
            model_name="samplegrant",
            name="resource",
            field=models.TextField(blank=True, default=""),
        ),
    ]
